config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :topics,  except: [:destroy]
  resources :interests, only: [:create]

  root "topics#index"

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic, counter_cache: true

  validates :level, inclusion: [1,2,3,4,5]
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, presence: true
  validates :focus_area, presence: true
  validates :description, presence: true

  has_many :interests
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:github]

 has_many :interests

  def self.from_omniauth(auth)
    user = where(provider: auth['provider'], uid: auth['uid']).first_or_create

    user.name         = auth.info.name
    user.email        = auth.info.email
    user.nickname     = auth.info.nickname
    user.access_token = auth.credentials.token
    user.password     = Devise.friendly_token[0,20]
    user.save!

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :authenticate_user!

  def create
     @interest = Interest.new(interest_params)
     @interest.user_id = current_user.id
    if @interest.valid?
       @interest.save

       redirect_to root_path
     else
       redirect_to root_path, alert: "Interest not created"
     end
   end

   private

   # Never trust parameters from the scary internet, only allow the white list through.
   def interest_params
     params.require(:interest).permit(:level, :comment, :topic_id)
   end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update]

  def index
    @topics = Topic.all
    @top_topics = Topic.order("interests_count DESC").limit(3)
    end

  def new
    @topic = Topic.new
    @top_topics = Topic.order("interests_count DESC").limit(3)

  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, filter_html: true, no_links: true)
    @top_topics = Topic.order("interests_count DESC").limit(3)

  end

  private
    def topic_params
      params.require(:topic).permit(:title, :description, :focus_area)
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Irontopics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'shared/navbar' %>
    <div class="container">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<!-- If signed in, columns and yield. If not signed in, entire width showing form -->
      <div class="col-xs-12 col-md-8">
        <%= yield %>
      </div>

      <div class="col-xs-6 col-md-3">
        <%= render 'shared/sidebar' %>
      </div>
    </div>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <p class="brand"> IRON<span class="brand_italic">topics</span> </p>
      </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
   </div> <!-- Navbar-header -->

    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= image_tag("yellow_profile.png", width:"50", class:"initial_icon") %></li>
          <li class="username"><%= current_user.name %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
   </div> <!-- Navbar-collapse -->

</nav>

<% if user_signed_in? %>
  <div class="tabs">
    <ul class="nav nav-tabs">
      <li role="presentation" class="active"><%= link_to 'All Topics', topics_path %>
        <!-- <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> -->
      </li>
      <li role="presentation" class="nav_tab"><%= link_to 'Add New Topic', new_topic_path %>
        <!-- <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> -->
      </li>
    </ul>
  </div>
<% else %>
<% end %>

app/views/shared/_sidebar.html.erb
<h6 class="sidebar_title"> Stats </h6>
<div class="stats">
  <ul class="stat_list">
    <li><span class="stat_number"><%= User.all.count %></span> Users</li>
    <li><span class="stat_number"><%= Topic.all.count %></span> Topics</li>
    <li><span class="stat_number"><%= Interest.all.count %></span> Interests</li>
  </ul>
</div>

<h6 class="sidebar_title"> Hot Topics </h6>
  <div class="hot_topics">
    <ul class="hot_topics_list">





    <li><span class="glyphicon glyphicon-fire" aria-hidden="true"></span> Most commented topic <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> #</li>
    <li><span class="glyphicon glyphicon-fire" aria-hidden="true"></span> Most commented topic <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> #</li>
    <li><span class="glyphicon glyphicon-fire" aria-hidden="true"></span> Most commented topic <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> #</li>
  </ul>
</div>

app/views/topics/_form.html.erb
<%= form_for :topic, url: topics_path , html:{class:"form-horizontal"} do |f| %>
  <div class="form-group">
    <div class="col-sm-7">
      <%= f.text_field :title , class:"form-control col-sm-8", :placeholder => 'Title' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-3">
      <%= f.text_field :focus_area , class:"form-control", :placeholder => 'Focus Area'  %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.text_area :description , class:"form-control", :placeholder => 'Description'  %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class:"btn btn-warning" %>
    </div>
  </div>

<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<% @topics.each do |topic| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <!-- LINK TO TOPIC  -->
      <%= image_tag("gray_profile.png", width:"80", class:"initial_icon float_left") %>

      <%= link_to topic , class:"topic_panel" do %>
        <ul>
          <li class="topic_title">
            <%= topic.title %>
            <span class="glyphicon glyphicon-comment float_right" aria-hidden="true">

              <% if topic.interests_count.nil? %>
                <span class="number_interests">0</span>
              <% else %>
                <span class="number_interests"><%= topic.interests_count %><span>
              <% end %>

            </span>
          </li>

          <li class="topic_info">
            <span class="focus"><%= topic.focus_area %></span> by <%= topic.user_id %> on <%= topic.created_at %>
          </li>
        </ul>
      <% end %>

    </div>
  </div>
<% end %>

app/views/topics/new.html.erb
<h1 class="heading">New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back to topics', topics_path %>
<p> How to add glyphicons here ^^ </p>

app/views/topics/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Focus area:</strong>
  <%= @topic.focus_area %>
</p>

<p>
  <strong>Description:</strong>
  <div class="markdown">
  <%= @markdown.render(@topic.description).html_safe %>
  </div>
</p>

<ul>
  <% @topic.interests.each do |interest| %>
    <li><%= interest.level %> by <%= interest.user.name %>. Comment: <%= @markdown.render(interest.comment).html_safe %></li>
  <% end %>
</ul>

<%= form_for(@topic.interests.new) do |f| %>
  <%= f.hidden_field :topic_id, value: @topic.id %>
  <div class="field">
  <%= f.label :level %>
  <%= f.text_field :level %>
  </div>
  <div class="field">
  <%= f.label :comment %>
  <%= f.text_area  :comment %>
  </div>
  <%= f.submit %>
<% end %>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>